# Generated by Django 5.1.4 on 2025-01-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read_by_admin', models.BooleanField(null=True, verbose_name='دیده شده / نشده')),
                ('response', models.TextField(blank=True, null=True, verbose_name='پاسخ به پیام کاربر')),
            ],
            options={
                'verbose_name': 'تماس باما',
                'verbose_name_plural': 'لیست تماس باما',
            },
        ),
    ]
